---
output: md_document 
---

`ecositer` is a collection of tools for the standardization and automation of vegetation data analysis. While the package is designed to work directly with datasets from the Natural Resources Conservation Service (NRCS), its functions are structured to apply broadly to vegetation datasets with similar structure.

The package supports workflows such as:
- Downloading and formatting publicly accessible NRCS vegetation data
- Quality control (QC) of vegetation data
- Ecological summary statistics by ecological site and state-and-transition models
- Exploratory ordination and community analysis

This package is intended for ecologists, natural resource managers, land owners, and anyone else interested working with plant community data.

contact nateroe@gmail.com with questions

## Installation

Get the development version from GitHub:

```r
remotes::install_github("natearoe/ecositer", dependencies = FALSE)
```

## Website
- GitHub repository - https://github.com/natearoe/ecositer
- Package website - https://natearoe.github.io/ecositer/

## Vignettes
- [Accessing vegetation data](https://natearoe.github.io/ecositer/articles/accessing_vegetation_data.html)
- [QCing vegetation data](https://natearoe.github.io/ecositer/articles/qc_vegetation_data.html) 
- [Summarizing ecological data](https://natearoe.github.io/ecositer/articles/summarizing_ecological_data.html)
- [Vegetation data ordination](https://natearoe.github.io/ecositer/articles/ordinating_vegetation_data.html)


